server:
  port: 8090

spring:
  application:
    name: api-weather-service
management:
  security:
    enabled: false

service:
   getHistoricUri: api/v1/weather/history/city/{city}/prediction/{prediction}
   getPredictionUri: api/v1/weather/{city}

dependencies:
   weatherServicePort: ${WEATHER_SERVICE_PORT:8091}
   weatherServiceId: ${WEATHER_SERVICE_ID:local-stack_weather-service}
